# Generated by Django 4.1.7 on 2023-04-06 08:39

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.upload_to),
        ),
    ]
